# User cible
TARGET_USER="${SUDO_USER:-deck}"

# Options
INSTALL_STEAM="true"
INSTALL_HEROIC="true"
USE_GAMESCOPE="true"

# Résolution cible
GAMESCOPE_RES_W="1280"
GAMESCOPE_RES_H="720"
GAMESCOPE_REFRESH="60"

# FEX
FEX_ROOTFS_DISTRO="ubuntu"
FEX_ROOTFS_VERSION="24.04"

# Logs
LOG_DIR="/var/log/switch-steamos"
